url: https://localhost:4000
baseurl:

# palette: http://paletton.com/palette.php?uid=53T0u0kn4uSdrKwiMArt0tcuamc

# Site settings
title: Peter Le
email: petele96@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://uk.linkedin.com/in/peter-le
  - title: github
    url: http://github.com/lep828

# Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
