url: https://thepeterle.com
baseurl:

# Site settings
title: Peter Le
email: petele96@gmail.com
description: "Web Developer in Surrey & London, United Kingdom. Always open to new opportunities, if you're interested get in touch."

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://linkedin.com/in/peter-le
  - title: github
    url: http://github.com/lep828

# Build settings
markdown: kramdown
permalink: pretty
